### ISSUE TITLE
Requests don't return

### ISSUE THREAD

**Issue by amcdnl** [axefrog/webpack-dnx-browsersync#1]
Have you experienced this when proxying? 

http://stackoverflow.com/questions/34025282/browser-sync-not-loading-asp-net-5-website-using-proxy
https://github.com/aspnet/KestrelHttpServer/issues/636

**Comment by axefrog** [comment]
Yep, it's an issue with Kestrel. Until RC2, you need to use WebListener while developing, and switch to Kestrel when deploying.

**Comment by amcdnl** [comment]
Yup, I actually found that after hunting forever today! Thanks for reply!
